### PR TITLE
SELinux support

### PR DESCRIPTION
**Pull request by darrell**
Hey, it looks like we weren't quite there on selinux. I've modified the .te file, and I think I've finally got it.  Though as you say, this should really be broken into its own domain.

### CODE REVIEW

**Comment by erikogan** [comment]
I'm sure I wrote a reply to this in May, I don't know why it didn't get posted.

This is exactly the change I was trying desperately to avoid. The problem with it is that just by installing mod_passenger we're giving all other code in the httpd (like mod_perl and mod_php) access to /bin/ps.

For most people running passenger that's probably ok, but I really don't like violating the principle of least surprise. Especially when it comes to security.

I think we need to sit down and put PassengerHelper into its own domain. I'd hoped to get a chance to do that before now, but now that CentOS 6 is imminent (and I have the packages building based on an accidentally exposed mirror) I should probably sit down and try it, to see how painful it will be.

**Comment by erikogan** [comment]
Last night’s 3.0.7-4 packages complete moving PassengerHelperAgent into its own domain. This should solve the SELinux problems. I've tested it on CentOS 6 & FC15.

Which distribution are you running?

And thank you for the submission and the prodding to do this the correct way. :)

**Comment by darrell** [comment]
I'm on CentOS 5. I'll get this pushed out today and see if any issues come up.

**Comment by erikogan** [comment]
Just one word of warning, if you’re running in permissive mode I think it turns off dont_audit policies so you can see EVERYTHING. Because ps traverses proc, that may cause an alarming number of denials for httpd_passenger_helper_t. I spent some time trying to quiet them while I debugged. 

You should be able to safely ignore them (or grep -v dev=proc) to remove them entirely. 

If I have some time today I'll try C5 as well. Which server are you using?

**Comment by erikogan** [comment]
Oh, and out of curiosity, are you pulling from the yum repository?

**Pull request closed without merging**
